on: [push]
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: latency-lingo/github-action@52fa4a0
        with:
          api-key: ${{ secrets.LATENCY_LINGO_API_KEY }}
          file: jmeter-results.jtl
          label: github-action-test
