on: [push]
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - name: install-cli
        run: curl -L https://github.com/AnthonyBobsin/latency-lingo-cli/releases/latest/download/latency-lingo-cli_Linux_x86_64.tar.gz | tar -xz
        shell: bash
      - name: publish-results-file
        # result={"runId":"ab8e928c-f250-4748-b3c9-ce657c493bd4","status":"pass","thresholds":[{"status":"pass","description":""}]}
        # result=`grep "Test run status" output.log | awk '{print $6}'`
        # echo "result=$result" >> $GITHUB_OUTPUT
        run: |
          ./latency-lingo-cli publish --file "${{ inputs.file }}" --api-key "$LATENCY_LINGO_API_KEY" --label "${{ inputs.label }}" --format "${{ inputs.format }}" --env "${{ inputs.env }}"
        env:
          LATENCY_LINGO_API_KEY: test
        shell: bash
      # - name: set-build-status
      #   run: |
      #     status=${{fromJson(steps.publish-results-file.outputs.result).status}}
      #     if [ $status = "pass" ]; then
      #       exit 0
      #     else
      #       exit 1
      #     fi
      #   shell: bash
      # - uses: latency-lingo/github-action@52fa4a09a2c3e359015b40996dcc0afdaf399088
      #   with:
      #     api-key: ${{ secrets.LATENCY_LINGO_API_KEY }}
      #     file: jmeter-results.jtl
      #     label: github-action-test
