on: [push]
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: latency-lingo/github-action@ed88152434c1bca9de3932a14d6245348a3aad17
        with:
          api-key: ${{ secrets.LATENCY_LINGO_API_KEY }}
          file: jmeter-results.jtl
          label: github-action-test
